GPTPHONE: ElevenLabsTTS Class Reference
ElevenLabsTTS Class Reference
Public Member Functions
__init__ (self)
set_voice (self, voice_id)
disconnect (self)
generate (self, Dict[str, Any] llm_reply, int interaction_count)
Public Member Functions inherited from AbstractTTSService
Public Member Functions inherited from EventHandler
on (self, str event, Callable callback)
createEvent (self, str event, *Any args, **Any kwargs)
on_event (self, event)
on_text_created (self, text)
on_text_delta (self, delta, snapshot)
on_text_done (self, text)
on_tool_call_created (self, tool_call)
on_tool_call_delta (self, delta, snapshot)
on_tool_call_done (self, tool_call)
submit_tool_outputs (self, tool_outputs)
Data Fields
voice_id = os.getenv("ELEVENLABS_VOICE_ID")
api_key = os.getenv("ELEVENLABS_API_KEY")
model_id = os.getenv("ELEVENLABS_MODEL_ID")
dict speech_buffer = {}
Data Fields inherited from EventHandler
list _events = []
client = client
Additional Inherited Members
Protected Member Functions inherited from EventHandler
_run_callback (self, Callable callback, *Any args, **Any kwargs)
Protected Attributes inherited from EventHandler
dict _events = {}
Detailed Description
A class representing the ElevenLabs Text-to-Speech (TTS) service.
Attributes:
    voice_id (str): The ID of the voice to be used for TTS.
    api_key (str): The API key for accessing the ElevenLabs TTS service.
    model_id (str): The ID of the TTS model to be used.
    speech_buffer (dict): A dictionary to store the generated speech audio.
Methods:
    set_voice(voice_id): Sets the voice ID for TTS.
    disconnect(): Disconnects from the ElevenLabs TTS service.
    generate(llm_reply, interaction_count): Generates speech audio based on the given partial response.
Constructor & Destructor Documentation
__init__()
__init__ (self)
Initializes an instance of the EventEmitter class.
Reimplemented from EventHandler.
    def __init__(self):
        super().__init__()
        self.voice_id = os.getenv("ELEVENLABS_VOICE_ID")
        self.api_key = os.getenv("ELEVENLABS_API_KEY")
        self.model_id = os.getenv("ELEVENLABS_MODEL_ID")
        self.speech_buffer = {}
References ElevenLabsTTS.__init__().
Referenced by ElevenLabsTTS.__init__().
Member Function Documentation
disconnect()
disconnect (self)
Disconnects from the ElevenLabs TTS service.
Note:
    The ElevenLabs client doesn't require explicit disconnection.
Reimplemented from AbstractTTSService.
    async def disconnect(self):
        """
        Disconnects from the ElevenLabs TTS service.
        Note:
            The ElevenLabs client doesn't require explicit disconnection.
        """
        logger.info("ElevenLabs TTS service disconnected")
        return
generate()
generate (self, Dict[str, Any] llm_reply, int interaction_count)
Generates speech audio based on the given partial response.
Args:
    llm_reply (Dict[str, Any]): The partial response received from the LLM service.
    interaction_count (int): The count of interactions.
Returns:
    None
Raises:
    Exception: If an error occurs in the ElevenLabs TTS service.
Reimplemented from AbstractTTSService.
    async def generate(self, llm_reply: Dict[str, Any], interaction_count: int):
        """
        Generates speech audio based on the given partial response.
        Args:
            llm_reply (Dict[str, Any]): The partial response received from the LLM service.
            interaction_count (int): The count of interactions.
        Returns:
            None
        Raises:
            Exception: If an error occurs in the ElevenLabs TTS service.
        """
        partial_response_index, partial_response = llm_reply['partialResponseIndex'], llm_reply['partialResponse']
        if not partial_response:
            return
        try:
            output_format = "ulaw_8000"
            url = f"https://api.elevenlabs.io/v1/text-to-speech/{self.voice_id}/stream"
            headers = {
                "xi-api-key": self.api_key,
                "Content-Type": "application/json",
                "Accept": "audio/wav"
            }
            params = {
                "output_format": output_format,
                "optimize_streaming_latency": 4
            }
            data = {
                "model_id": self.model_id,
                "text": partial_response
            }
            async with aiohttp.ClientSession() as session:
                async with session.post(url, headers=headers, params=params, json=data) as response:
                    if response.status == 200:
                        audio_content = await response.read()
                        audio_base64 = base64.b64encode(audio_content).decode('utf-8')
                        await self.createEvent('speech', partial_response_index, audio_base64, partial_response,
                                               interaction_count)
        except Exception as err:
            logger.error("Error occurred in ElevenLabs TTS service", exc_info=True)
            logger.error(str(err))
References ElevenLabsTTS.api_key, EventHandler.createEvent(), and ElevenLabsTTS.model_id.
set_voice()
set_voice (self, voice_id)
Sets the voice ID for TTS.
Args:
    voice_id (str): The ID of the voice to be used for TTS.
Reimplemented from AbstractTTSService.
    def set_voice(self, voice_id):
        """
        Sets the voice ID for TTS.
        Args:
            voice_id (str): The ID of the voice to be used for TTS.
        """
        self.voice_id = voice_id
References ElevenLabsTTS.voice_id.
Field Documentation
api_key
api_key = os.getenv("ELEVENLABS_API_KEY")
Referenced by ElevenLabsTTS.generate().
model_id
model_id = os.getenv("ELEVENLABS_MODEL_ID")
Referenced by ElevenLabsTTS.generate().
speech_buffer
dict speech_buffer = {}
voice_id
voice_id = os.getenv("ELEVENLABS_VOICE_ID")
Referenced by ElevenLabsTTS.set_voice().
The documentation for this class was generated from the following file:
/Users/seanbaker/Downloads/GPTPhone (2)/services/tts_service.py