GPTPHONE: EventHandler Class Reference
EventHandler Class Reference
Public Member Functions
__init__ (self)
on_event (self, event)
on_text_created (self, text)
on_text_delta (self, delta, snapshot)
on_text_done (self, text)
on_tool_call_created (self, tool_call)
on_tool_call_delta (self, delta, snapshot)
on_tool_call_done (self, tool_call)
format_annotation (self, text)
create_file_link (self, file_name, file_id)
Data Fields
dict session_state
Detailed Description
Class EventHandler
This class is a subclass of the openai.AssistantEventHandler class and contains various methods that handle different events related to the OpenAI Assistant.
Attributes:
- session_state (dict): A dictionary that stores the current state of the session, including chat log, tool calls, current message, current markdown, current tool input, and current tool input markdown.
Methods:
- on_event(event): Handles the general event. This method is not implemented in the EventHandler class and needs to be overridden in a subclass.
- on_text_created(text): Handles the event when a new text is created. It sets the current message to empty and prints "Assistant:".
- on_text_delta(delta, snapshot): Handles the event when a delta change is made to the text. It updates the current message in the session state and prints the updated text.
- on_text_done(text): Handles the event when the text is complete. It formats the annotation in the text, prints the formatted text, and appends it to the chat log in the session state.
- on_tool_call_created(tool_call): Handles the event when a tool call is created. If the tool call is of type "code_interpreter", it sets the current tool input to empty and prints "Assistant:".
- on_tool_call_delta(delta, snapshot): Handles the event when a delta change is made to the tool call. If the delta is of type "code_interpreter", it updates the current tool input in the session state and prints the input code.
- on_tool_call_done(tool_call): Handles the event when the tool call is complete. It appends the tool call to the tool calls list in the session state. If the tool call is of type "code_interpreter", it prints the input code and outputs.
- format_annotation(text): Formats the annotation in the given text by replacing annotation texts with numbered references and creating download links for file citations. Returns the formatted text.
- create_file_link(file_name, file_id): Creates a download link for the given file name and file ID. Returns the link tag.
Note: This class needs to be subclassed and the on_event() method needs to be implemented in the subclass.
Constructor & Destructor Documentation
__init__()
__init__ (self)
    def __init__(self):
        super().__init__()
        self.session_state = {
            "chat_log": [],
            "tool_calls": [],
            "current_message": "",
            "current_markdown": "",
            "current_tool_input": "",
            "current_tool_input_markdown": ""
        }
References EventHandler.__init__().
Referenced by EventHandler.__init__().
Member Function Documentation
create_file_link()
create_file_link (self, file_name, file_id)
    def create_file_link(self, file_name, file_id):
        content = client.files.content(file_id)
        content_type = content.response.headers["content-type"]
        b64 = base64.b64encode(content.text.encode(content.encoding)).decode()
        link_tag = f'<a href="data:{content_type};base64,{b64}" download="{file_name}">Download Link</a>'
        return link_tag
@log_function_call
Referenced by EventHandler.format_annotation().
format_annotation()
format_annotation (self, text)
    def format_annotation(self, text):
        citations = []
        text_value = text.value
        for index, annotation in enumerate(text.annotations):
            text_value = text_value.replace(annotation.text, f" [{index}]")
            if file_citation := getattr(annotation, "file_citation", None):
                cited_file = client.files.retrieve(file_citation.file_id)
                citations.append(
                    f"[{index}] {file_citation.quote} from {cited_file.filename}"
                )
            elif file_path := getattr(annotation, "file_path", None):
                link_tag = self.create_file_link(
                    annotation.text.split("/")[-1],
                    file_path.file_id,
                )
                text_value = re.sub(r"\[(.*?)\]\s*\‍(\s*(.*?)\s*\‍)", link_tag, text_value)
        text_value += "\n\n" + "\n".join(citations)
        return text_value
References EventHandler.create_file_link().
Referenced by EventHandler.on_text_done().
on_event()
on_event (self, event)
    def on_event(self, event):
        pass
on_text_created()
on_text_created (self, text)
    def on_text_created(self, text):
        self.session_state["current_message"] = ""
        print("Assistant:")
References EventHandler.session_state.
on_text_delta()
on_text_delta (self, delta, snapshot)
    def on_text_delta(self, delta, snapshot):
        if snapshot.value:
            text_value = re.sub(
                r"\[(.*?)\]\s*\‍(\s*(.*?)\s*\‍)", "Download Link", snapshot.value
            )
            self.session_state["current_message"] = text_value
            print(text_value, end="", flush=True)
References EventHandler.session_state.
on_text_done()
on_text_done (self, text)
    def on_text_done(self, text):
        format_text = self.format_annotation(text)
        print("\n" + format_text)
        self.session_state["chat_log"].append({"name": "assistant", "msg": format_text})
References EventHandler.format_annotation(), and EventHandler.session_state.
on_tool_call_created()
on_tool_call_created (self, tool_call)
    def on_tool_call_created(self, tool_call):
        if tool_call.type == "code_interpreter":
            self.session_state["current_tool_input"] = ""
            print("Assistant:")
References EventHandler.session_state.
on_tool_call_delta()
on_tool_call_delta (self, delta, snapshot)
    def on_tool_call_delta(self, delta, snapshot):
        if delta.type == "code_interpreter":
            if delta.code_interpreter.input:
                self.session_state["current_tool_input"] += delta.code_interpreter.input
                input_code = f"### code interpreter\ninput:\n```python\n{self.session_state['current_tool_input']}\n```"
                print(input_code, end="", flush=True)
            if delta.code_interpreter.outputs:
                for output in delta.code_interpreter.outputs:
                    if output.type == "logs":
                        pass
References EventHandler.session_state.
on_tool_call_done()
on_tool_call_done (self, tool_call)
    def on_tool_call_done(self, tool_call):
        self.session_state["tool_calls"].append(tool_call)
        if tool_call.type == "code_interpreter":
            input_code = f"### code interpreter\ninput:\n```python\n{tool_call.code_interpreter.input}\n```"
            print(input_code)
            for output in tool_call.code_interpreter.outputs:
                if output.type == "logs":
                    output = f"### code interpreter\noutput:\n```\n{output.logs}\n```"
                    print(output)
        elif (
                tool_call.type == "function"
                and self.current_run.status == "requires_action"
        ):
            msg = f"### Function Calling: {tool_call.function.name}"
            print(msg)
            self.session_state["chat_log"].append({"name": "assistant", "msg": msg})
            tool_calls = self.current_run.required_action.submit_tool_outputs.tool_calls
            tool_outputs = []
            for submit_tool_call in tool_calls:
                tool_function_name = submit_tool_call.function.name
                tool_function_arguments = json.loads(
                    submit_tool_call.function.arguments
                )
                tool_function_output = TOOL_MAP[tool_function_name](
                    **tool_function_arguments
                )
                tool_outputs.append(
                    {
                        "tool_call_id": submit_tool_call.id,
                        "output": tool_function_output,
                    }
                )
            with client.beta.threads.runs.submit_tool_outputs_stream(
                    thread_id=thread.id,
                    run_id=self.current_run.id,
                    tool_outputs=tool_outputs,
                    event_handler=EventHandler(),
            ) as stream:
                stream.until_done()
References EventHandler.session_state.
Field Documentation
session_state
dict session_state
Initial value:
=  {
            "chat_log": [],
            "tool_calls": [],
            "current_message": "",
            "current_markdown": "",
            "current_tool_input": "",
            "current_tool_input_markdown": ""
        }
Referenced by EventHandler.on_text_created(), EventHandler.on_text_delta(), EventHandler.on_text_done(), EventHandler.on_tool_call_created(), EventHandler.on_tool_call_delta(), and EventHandler.on_tool_call_done().
The documentation for this class was generated from the following file:
/Users/seanbaker/Downloads/GPTPhone (2)/Assistants.py