GPTPHONE: /Users/seanbaker/Downloads/GPTPhone (2)/debug.cpp File Reference
debug.cpp File Reference
#include <iostream>
#include <functional>
#include <chrono>
Macros
#define ENABLE_DEBUG true
Functions
template<typename Func , typename... Args>
auto timer (Func &&func, Args &&... args)
template<typename Func , typename... Args>
auto log_function_call (Func &&func, bool enable_timer=true, Args &&... args)
int example_function (int a, int b)
int main ()
Macro Definition Documentation
ENABLE_DEBUG
#define ENABLE_DEBUG true
Referenced by log_function_call().
Function Documentation
example_function()
int example_function (int a, int b)
{
    return a + b;
}
Referenced by main().
log_function_call()
template<typename Func , typename... Args> auto log_function_call (Func && func, bool enable_timer = true, Args &&... args)
{
    if (ENABLE_DEBUG) {
        std::cout << "Calling function...\n";
        if (enable_timer) {
            return timer(std::forward<Func>(func), std::forward<Args>(args)...);
        } else {
            return std::invoke(std::forward<Func>(func), std::forward<Args>(args)...);
        }
    } else {
        return std::invoke(std::forward<Func>(func), std::forward<Args>(args)...);
    }
}
References ENABLE_DEBUG, and timer().
Referenced by main().
main()
int main ()
           {
    auto result = log_function_call(example_function, true, 2, 3);
    std::cout << "Result: " << result << '\n';
    return 0;
}
References example_function(), and log_function_call().
timer()
template<typename Func , typename... Args> auto timer (Func && func, Args &&... args)
{
    auto start = std::chrono::high_resolution_clock::now();
    auto result = std::invoke(std::forward<Func>(func), std::forward<Args>(args)...);
    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> elapsed = end - start;
    std::cout << "Function execution took " << elapsed.count() << " seconds\n";
    return result;
}
Referenced by log_function_call().