GPTPHONE: Assistants Namespace Reference
Assistants Namespace Reference
Data Structures
class EventHandler
Functions
str_to_bool (str_input)
create_thread (content, file)
create_message (thread, content, file)
run_stream (user_input, file, selected_assistant_id)
main ()
Variables
logger = get_logger(__name__)
openai_api_key = os.environ.get("OPENAI_API_KEY")
azure_openai_endpoint = os.environ.get("AZURE_OPENAI_ENDPOINT")
azure_openai_key = os.environ.get("AZURE_OPENAI_KEY")
client = None
Function Documentation
create_message()
create_message (thread, content, file)
:param thread: A Thread object representing the thread where the message will be created.
:param content: A string representing the content of the message.
:param file: An optional File object representing a file attachment for the message.
:return: None
This method creates a message in a given thread using the provided content and file attachment, if any. If a file attachment is provided, it is added to the message as an attachment with specific tools associated with it. The message is created using the client.beta.threads.messages.create() method, specifying the thread id, role, content, and attachments parameters.
def create_message(thread, content, file):
    """
    :param thread: A Thread object representing the thread where the message will be created.
    :param content: A string representing the content of the message.
    :param file: An optional File object representing a file attachment for the message.
    :return: None
    This method creates a message in a given thread using the provided content and file attachment, if any. If a file attachment is provided, it is added to the message as an attachment with specific tools associated with it. The message is created using the client.beta.threads.messages.create() method, specifying the thread id, role, content, and attachments parameters.
    """
    attachments = []
    if file is not None:
        attachments.append(
            {"file_id": file.id, "tools": [{"type": "code_interpreter"}, {"type": "file_search"}]}
        )
    client.beta.threads.messages.create(
        thread_id=thread.id, role="user", content=content, attachments=attachments
    )
@log_function_call
Referenced by run_stream().
create_thread()
create_thread (content, file)
:param content: The content of the thread.
:param file: The file associated with the thread.
:return: The created thread.
def create_thread(content, file):
    """
    :param content: The content of the thread.
    :param file: The file associated with the thread.
    :return: The created thread.
    """
    return client.beta.threads.create()
@log_function_call
Referenced by run_stream().
main()
main ()
Entry point for the program.
:return: None
def main():
    """
    Entry point for the program.
    :return: None
    """
    # Simulate user input and assistant interaction
    user_input = input("You: ")
    assistant_id = os.environ.get("ASSISTANT_ID", "default_assistant")
    # Simulate a file upload (disabled in this example)
    uploaded_file = None
    # Run the stream
    while user_input != "q":
        run_stream(user_input, uploaded_file, assistant_id)
        user_input = input("You: ")
References main(), and run_stream().
Referenced by main().
run_stream()
run_stream (user_input, file, selected_assistant_id)
:param user_input: The input from the user.
:param file: The file to be processed.
:param selected_assistant_id: The ID of the selected assistant.
:return: None
This method runs a stream for a chat session using the given user input, file, and selected assistant ID. It creates a thread, sends messages to the thread, and handles events using the event handler. The chat log is printed at the end of the session.
def run_stream(user_input, file, selected_assistant_id):
    """
    :param user_input: The input from the user.
    :param file: The file to be processed.
    :param selected_assistant_id: The ID of the selected assistant.
    :return: None
    This method runs a stream for a chat session using the given user input, file, and selected assistant ID. It creates a thread, sends messages to the thread, and handles events using the event handler. The chat log is printed at the end of the session.
    """
    thread = create_thread(user_input, file)
    create_message(thread, user_input, file)
    event_handler = EventHandler()  # Create an instance of the event handler with session state
    with client.beta.threads.runs.stream(
            thread_id=thread.id,
            assistant_id=selected_assistant_id,
            event_handler=event_handler,
    ) as stream:
        stream.until_done()
    # Access the session state from the event handler if needed
    session_state = event_handler.session_state
    print("\nFinal Chat Log:")
    for log in session_state["chat_log"]:
        print(f"{log['name']}: {log['msg']}")
References create_message(), and create_thread().
Referenced by main().
str_to_bool()
str_to_bool (str_input)
Convert a string to a boolean value.
:param str_input: The string to convert.
:return: The boolean value converted from the string.
def str_to_bool(str_input):
    """
    Convert a string to a boolean value.
    :param str_input: The string to convert.
    :return: The boolean value converted from the string.
    """
    if not isinstance(str_input, str):
        return False
    return str_input.lower() == "true"
# Load environment variables
Variable Documentation
azure_openai_endpoint
azure_openai_endpoint = os.environ.get("AZURE_OPENAI_ENDPOINT")
azure_openai_key
azure_openai_key = os.environ.get("AZURE_OPENAI_KEY")
client
client = None
logger
logger = get_logger(__name__)
openai_api_key
openai_api_key = os.environ.get("OPENAI_API_KEY")