GPTPHONE: logger_config Namespace Reference
logger_config Namespace Reference
Functions
get_logger (name)
log_function_call (func, debug=DEBUG_SERVICES)
timer (func)
wrap_functions_in_module (module_name, debug)
wrap_services ()
Variables
format
level
colorize
str DEBUG_APP = 'true'
str DEBUG_SERVICES = 'true'
str OTHER_SERVICES_DEBUG = 'true'
SERVICES = os.getenv('SERVICES', '').split(',')
Function Documentation
get_logger()
get_logger (name)
A method to get a logger object.
:param name: The name of the logger.
:return: The logger object.
def get_logger(name):
    """
    A method to get a logger object.
    :param name: The name of the logger.
    :return: The logger object.
    """
    return logger.bind(name=name)
log_function_call()
log_function_call (func, debug = DEBUG_SERVICES)
Log Function Call
This function is used to log the call and duration of a given function. It wraps the function with a logging mechanism.
:param func: The function to be wrapped and logged.
:param debug: Boolean indicating whether logging is enabled or not. Default is `DEBUG_SERVICES`.
:return: Wrapped function with logging mechanism.
Example Usage:
```
@log_function_call
def my_function():
    return "Hello World"
logged_func = log_function_call(my_function, debug=True)
logged_func()
```
def log_function_call(func, debug=DEBUG_SERVICES):
    """
    Log Function Call
    This function is used to log the call and duration of a given function. It wraps the function with a logging mechanism.
    :param func: The function to be wrapped and logged.
    :param debug: Boolean indicating whether logging is enabled or not. Default is `DEBUG_SERVICES`.
    :return: Wrapped function with logging mechanism.
    Example Usage:
    ```
    @log_function_call
    def my_function():
        return "Hello World"
    logged_func = log_function_call(my_function, debug=True)
    logged_func()
    ```
    """
    if debug:
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            logger.info(f"Calling function: {func.__name__} with args: {args} and kwargs: {kwargs}")
            start_time = time.time()
            if asyncio.iscoroutinefunction(func):
                # If the function is a coroutine, return an async wrapper
                @functools.wraps(func)
                async def async_wrapper(*args, **kwargs):
                    result = await func(*args, **kwargs)
                    end_time = time.time()
                    duration = end_time - start_time
                    logger.info(f"Function {func.__name__} completed with result: {result} in {duration:.4f} seconds")
                    return result
                return async_wrapper(*args, **kwargs)
            else:
                # If the function is synchronous, call it normally
                result = func(*args, **kwargs)
                end_time = time.time()
                duration = end_time - start_time
                logger.info(f"Function {func.__name__} completed with result: {result} in {duration:.4f} seconds")
                return result
        return wrapper
    else:
        return func
timer()
timer (func)
:param func: The function to be timed.
:return: The result of the function.
This method is a decorator that times the execution of a given function. It wraps the function with a timer and logs the elapsed time using the logger module. The timer uses the `perf_counter()` method from the `time` module to measure the elapsed time.
Usage:
    @timer
    def my_function():
        # code to be timed
Example:
    @timer
    def fibonacci(n):
        if n <= 1:
            return n
        else:
            return fibonacci(n-1) + fibonacci(n-2)
Note: The logger module must be properly configured before using the `timer` decorator. It's recommended to initialize the logger in the calling module before using this decorator.
def timer(func):
    """
    :param func: The function to be timed.
    :return: The result of the function.
    This method is a decorator that times the execution of a given function. It wraps the function with a timer and logs the elapsed time using the logger module. The timer uses the `perf_counter()` method from the `time` module to measure the elapsed time.
    Usage:
        @timer
        def my_function():
            # code to be timed
    Example:
        @timer
        def fibonacci(n):
            if n <= 1:
                return n
            else:
                return fibonacci(n-1) + fibonacci(n-2)
    Note: The logger module must be properly configured before using the `timer` decorator. It's recommended to initialize the logger in the calling module before using this decorator.
    """
    @functools.wraps(func)
    def wrapper_timer(*args, **kwargs):
        start_time = time.perf_counter()  # Start the timer
        result = func(*args, **kwargs)
        end_time = time.perf_counter()  # End the timer
        run_time = end_time - start_time  # Calculate the elapsed time
        logger.info(f"Function {func.__name__!r} took {run_time:.4f} seconds")
        return result
    return wrapper_timer
Referenced by wrap_functions_in_module().
wrap_functions_in_module()
wrap_functions_in_module (module_name, debug)
Wrap Functions in Module
:param module_name: The name of the module to be wrapped.
:type module_name: str
:param debug: Whether to enable debug mode.
:type debug: bool
:return: The wrapped module.
:rtype: module
def wrap_functions_in_module(module_name, debug):
    """
    Wrap Functions in Module
    :param module_name: The name of the module to be wrapped.
    :type module_name: str
    :param debug: Whether to enable debug mode.
    :type debug: bool
    :return: The wrapped module.
    :rtype: module
    """
    module = importlib.import_module(module_name)
    for attr_name in dir(module):
        attr = getattr(module, attr_name)
        print("Wrapping {}".format(attr_name))
        if isinstance(attr, types.FunctionType):
            wrapped_func = log_function_call(attr, debug)
            wrapped_func = timer(wrapped_func)
            setattr(module, attr_name, wrapped_func)
    return module
# Create a function to wrap all specified service modules
References format, and timer().
Referenced by wrap_services().
wrap_services()
wrap_services ()
Wrap Services Function
=====================
This function is used to wrap services.
Returns:
    None
def wrap_services():
    """
    Wrap Services Function
    =====================
    This function is used to wrap services.
    Returns:
        None
    """
    for service in SERVICES:
        if DEBUG_SERVICES:
            wrap_functions_in_module(service, DEBUG_SERVICES)
        else:
            wrap_functions_in_module(service, OTHER_SERVICES_DEBUG)
    # Wrap the `app` module if DEBUG_APP is enabled
    if DEBUG_APP:
        wrap_functions_in_module('app', DEBUG_APP)
References wrap_functions_in_module().
Variable Documentation
colorize
colorize
DEBUG_APP
str DEBUG_APP = 'true'
DEBUG_SERVICES
str DEBUG_SERVICES = 'true'
format
format
Referenced by wrap_functions_in_module().
level
level
OTHER_SERVICES_DEBUG
str OTHER_SERVICES_DEBUG = 'true'
SERVICES
SERVICES = os.getenv('SERVICES', '').split(',')