GPTPHONE: AssistantsAsync Namespace Reference
AssistantsAsync Namespace Reference
Data Structures
class EventHandler
Functions
str_to_bool (str_input)
create_thread (content, file)
create_message (thread, content, file)
run_stream (user_input, file, selected_assistant_id)
main ()
Variables
logger = get_logger(__name__)
openai_api_key = os.environ.get("OPENAI_API_KEY")
azure_openai_endpoint = os.environ.get("AZURE_OPENAI_ENDPOINT")
azure_openai_key = os.environ.get("AZURE_OPENAI_KEY")
client = AsyncOpenAI(api_key=openai_api_key)
Function Documentation
create_message()
create_message (thread, content, file)
Create a message and send it to the specified thread.
:param thread: The thread object representing the thread where the message will be sent.
:type thread: Thread
:param content: The content of the message.
:type content: str
:param file: The file object representing the file to be attached to the message. (optional)
:type file: File
:return: None
:rtype: None
async def create_message(thread, content, file):
    """
    Create a message and send it to the specified thread.
    :param thread: The thread object representing the thread where the message will be sent.
    :type thread: Thread
    :param content: The content of the message.
    :type content: str
    :param file: The file object representing the file to be attached to the message. (optional)
    :type file: File
    :return: None
    :rtype: None
    """
    attachments = []
    if file is not None:
        attachments.append(
            {"file_id": file.id, "tools": [{"type": "code_interpreter"}, {"type": "file_search"}]}
        )
    await client.beta.threads.messages.create(
        thread_id=thread.id, role="user", content=content, attachments=attachments
    )
Referenced by run_stream().
create_thread()
create_thread (content, file)
:param content: The content of the thread to be created.
:param file: The file associated with the thread (optional).
:return: A coroutine that creates a new thread using the specified content and file (if provided). The thread is created asynchronously.
async def create_thread(content, file):
    """
    :param content: The content of the thread to be created.
    :param file: The file associated with the thread (optional).
    :return: A coroutine that creates a new thread using the specified content and file (if provided). The thread is created asynchronously.
    """
    return await client.beta.threads.create()
@log_function_call
Referenced by run_stream().
main()
main ()
Main method for running the assistant interaction.
:return: None
async def main():
    """
    Main method for running the assistant interaction.
    :return: None
    """
    # Simulate user input and assistant interaction
    user_input = input("You: ")
    assistant_id = os.environ.get("ASSISTANT_ID", "default_assistant")
    # Simulate a file upload (disabled in this example)
    uploaded_file = None
    # Run the stream
    while user_input != "q":
        await run_stream(user_input, uploaded_file, assistant_id)  # Await the async run_stream
        user_input = input("You: ")
References main(), and run_stream().
Referenced by main().
run_stream()
run_stream (user_input, file, selected_assistant_id)
Runs a stream of events for a chat assistant.
:param user_input: The user input for the chat assistant.
:type user_input: str
:param file: The file associated with the user input.
:type file: str
:param selected_assistant_id: The ID of the selected chat assistant.
:type selected_assistant_id: str
:return: None
async def run_stream(user_input, file, selected_assistant_id):
    """
    Runs a stream of events for a chat assistant.
    :param user_input: The user input for the chat assistant.
    :type user_input: str
    :param file: The file associated with the user input.
    :type file: str
    :param selected_assistant_id: The ID of the selected chat assistant.
    :type selected_assistant_id: str
    :return: None
    """
    thread = await create_thread(user_input, file)
    await create_message(thread, user_input, file)
    event_handler = EventHandler()  # Create an instance of the event handler with session state
    # Use the AsyncAssistantStreamManager to manage the stream asynchronously
    async with client.beta.threads.runs.stream(
        thread_id=thread.id,
        assistant_id=selected_assistant_id,
        event_handler=event_handler,
    ) as stream:
        async for event in stream:
            # Process each event as it arrives
            pass
    # Access the session state from the event handler if needed
    session_state = event_handler.session_state
    print("\nFinal Chat Log:")
    for log in session_state["chat_log"]:
        print(f"{log['name']}: {log['msg']}")
References create_message(), and create_thread().
Referenced by main().
str_to_bool()
str_to_bool (str_input)
Converts a string input to a boolean value.
:param str_input: The string input to be converted.
:return: The boolean value.
def str_to_bool(str_input):
    """
    Converts a string input to a boolean value.
    :param str_input: The string input to be converted.
    :return: The boolean value.
    """
    if not isinstance(str_input, str):
        return False
    return str_input.lower() == "true"
Variable Documentation
azure_openai_endpoint
azure_openai_endpoint = os.environ.get("AZURE_OPENAI_ENDPOINT")
azure_openai_key
azure_openai_key = os.environ.get("AZURE_OPENAI_KEY")
client
client = AsyncOpenAI(api_key=openai_api_key)
logger
logger = get_logger(__name__)
openai_api_key
openai_api_key = os.environ.get("OPENAI_API_KEY")